default:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s [%(module)s] [%(levelname)s] - %(message)s"
  handlers:
    console_handler:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
    file_handler:
      class: logging.FileHandler
      filename: idstools.log
      level: DEBUG
      formatter: simple
    data_explorer_handler:
      class: logging.FileHandler
      filename: default.log
      level: DEBUG
      formatter: simple
    data_preparation_handler:
      class: logging.FileHandler
      filename: default.log
      level: DEBUG
      formatter: simple
    model_optimization_handler:
      class: logging.FileHandler
      filename: default.log
      level: DEBUG
      formatter: simple
  loggers:
    idstools:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools._config:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools._helpers:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools.data_explorer:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools.data_preparation:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools.wrapper:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    tqdm:
      level: INFO
      handlers: [file_handler, console_handler]
      propagate: False
    data_explorer_results:
      level: INFO
      handlers: [data_explorer_handler]
      propagate: False
    data_preparation_results:
      level: INFO
      handlers: [data_preparation_handler]
      propagate: False
    model_optimization_results:
      level: INFO
      handlers: [model_optimization_handler]
      propagate: False
    root:
      level: INFO
      handlers: [file_handler]