default:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s [%(module)s] [%(levelname)s] - %(message)s"
  handlers:
    console_handler:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
    file_handler:
      class: logging.FileHandler
      filename: idstools.log
      level: DEBUG
      formatter: simple
    exploration_handler:
      class: logging.FileHandler
      filename: default.log
      level: DEBUG
      formatter: simple
    preparation_handler:
      class: logging.FileHandler
      filename: default.log
      level: DEBUG
      formatter: simple
    optimization_handler:
      class: logging.FileHandler
      filename: default.log
      level: DEBUG
      formatter: simple
  loggers:
    idstools:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools._config:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools._helpers:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools.data_explorer:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools.data_preparation:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    idstools.wrapper:
      level: DEBUG
      handlers: [file_handler, console_handler]
      propagate: False
    tqdm:
      level: INFO
      handlers: [file_handler, console_handler]
      propagate: False
    exploration_results:
      level: INFO
      handlers: [exploration_handler]
      propagate: False
    preparation_results:
      level: INFO
      handlers: [preparation_handler]
      propagate: False
    optimization_results:
      level: INFO
      handlers: [optimization_handler]
      propagate: False
    root:
      level: INFO
      handlers: [file_handler]