default:
  Target_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"
        features: ['registered', 'temp', 'atemp', 'windspeed', 'season', 'yr', 'mnth', 'weekday', 'weathersit']
  
  Validation_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_test.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"
        features: ['registered', 'temp', 'atemp', 'windspeed', 'season', 'yr', 'mnth', 'weekday', 'weathersit']

Task1:
  01_Data_Exploration:
    data_explorer:
      DataExplorer:
        target: Target_Data
        pipeline:
          descriptive_analysis: true
          missing_value_analysis: true
          outlier_analysis: true
          distribution_analysis: true
          scatter_analysis: true
          correlation_analysis: true
          calculate_correlation: true
  
  02_Transform_dteday_to_datetime:
    data_preparation:
      DataPreparation:
        target: Target_Data
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: idstools._transformer
              config:
                target: dteday
                format: "%d.%m.%Y"
  
  03_Time_Series_Analysis:
    data_explorer:
      DataExplorer:
        target: Target_Data
        pipeline:
          time_series_analysis: true