default:
  Target_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"

Task1:
  01_Data_Exploration:
    data_explorer:
      DataExplorer:
        pipeline:
          descriptive_analysis: true
          missing_value_analysis: true
          outlier_analysis: true
          distribution_analysis: true
          scatter_analysis: true
          correlation_analysis: true
          calculate_correlation: true
  
  02_Data_Preparation:
    data_preparation:
      DataPreparation:
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: idstools._transformer
              config:
                target: dteday
                format: "%d.%m.%Y"
          _NaNDropper:
            - target: hum
            - target: season

  03_Data_Exploration:
    data_explorer:
      DataExplorer:
        pipeline:
          time_series_analysis: true
          variance_inflation_factor: true

Task2:
  01_Minimal_Preparation:
    data_preparation:
      DataPreparation:
        pipeline:
          _FeatureDropper:
            - target: casual
              config:
                axis: 1
                errors: "ignore"
            - target: registered
              config:
                axis: 1
                errors: "ignore"

  02_Baseline_Regression_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validate_models: true

  03_Impute_NaN_Values_Mean:
    data_preparation:
      DataPreparation:
        pipeline:
          _SimpleImputer:
            - target: hum
              config:
                strategy: mean
          _CustomTransformer:
            - func: encode_season
              module: idstools._transformer
              config:
                target: dteday

  04_Baseline_Regression_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validate_models: true

  05_Reset_Data:
    Target_Data:
      _objects:
        Target:
          input_path: "results/TASK2/01_Minimal_Preparation/BikeRentalDaily_train_processed.csv"
          input_delimiter: ";"
          index: "instant"
          label: "cnt"

  06_Impute_NaN_Values_Median:
    data_preparation:
      DataPreparation:
        pipeline:
          _SimpleImputer:
            - target: hum
              config:
                strategy: median
          _CustomTransformer:
            - func: encode_season
              module: idstools._transformer
              config:
                target: dteday

  07_Baseline_Regression_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validate_models: true

  08_Windspeed_Imputation:
    data_preparation:
      DataPreparation:
        pipeline:
          _CustomTransformer:
            - func: negative_to_nan
              module: idstools._transformer
              config:
                target: windspeed
          _SimpleImputer:
            - target: windspeed
              config:
                strategy: mean

  09_Baseline_Regression_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validate_models: true