default:
  Initialize_Target_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"
        features: ["season", "yr", "mnth", "holiday", "weekday", "workingday", "weathersit", "temp", "atemp", "hum", "windspeed"]

  Explore_Data:
    data_explorer:
      DataExplorer:
        pipeline:
          correlation_analysis: true

  Drop_Multi_Collinear_Features:
    data_preparation:
      DataPreparation:
        pipeline:
          _FeatureDropper:
            - target: atemp
              config:
                axis: 1
                errors: "ignore"
          _NaNDropper:
            - target: hum
              config:
                axis: 1
                errors: "ignore"
            - target: season
              config:
                axis: 1
                errors: "ignore"
                
    data_explorer:
      DataExplorer:
        pipeline:
          correlation_analysis: true
          vaiance_inflation_factor: true

  Transform_dteday_to_datetime:
    data_preparation:
      DataPreparation:
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: idstools._transformer
              config:
                target: dteday
                format: "%d.%m.%Y"

  Evaluate_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validation: true