default:
  Target_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"
        features: ['registered', 'temp', 'atemp', 'windspeed', 'season', 'yr', 'mnth', 'weekday', 'weathersit']

Task1:
  01_Data_Exploration:
    data_explorer:
      DataExplorer:
        pipeline:
          descriptive_analysis: true
          missing_value_analysis: true
          outlier_analysis: true
          distribution_analysis: true
          scatter_analysis: true
          correlation_analysis: true
          calculate_correlation: true
  
  02_Transform_dteday_to_datetime:
    data_preparation:
      DataPreparation:
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: idstools._transformer
              config:
                target: dteday
                format: "%d.%m.%Y"
  
  03_Time_Series_Analysis:
    data_explorer:
      DataExplorer:
        pipeline:
          time_series_analysis: true

Task2:  
  01_Baseline_Regression_Preprocessing:
    data_preparation:
      DataPreparation:
        pipeline:
          _SimpleImputer:
            - target: hum
              config:
                strategy: "mean"
            - target: season
              config:
                strategy: "mean"
  
  02_Data_Exploration:
    data_explorer:
      DataExplorer:
        pipeline:
          descriptive_analysis: true
          missing_value_analysis: true
          calculate_correlation: true

  03_Baseline_Regression_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validation: true