default:
  Target_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"

Task1:
  Initial_Exploration:
    data_explorer:
      DataExplorer:
        pipeline:
          descriptive_analysis: true
          missing_value_analysis: true
          outlier_analysis: true
          distribution_analysis: true
          scatter_analysis: true
          correlation_analysis: true
          calculate_correlation: true

Task2:
  Linear_Regression_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"
        features: ["season", "yr", "mnth", "holiday", "weekday", "workingday", "weathersit", "temp", "atemp", "hum", "windspeed"]
  
  Linear_Regression_Preprocessing:
    data_preparation:
      DataPreparation:
        pipeline:
          _FeatureDropper:
            - target: atemp
              config:
                axis: 1
                errors: "ignore"
            - target: mnth
              config:
                axis: 1
                errors: "ignore"
            - target: workingday
              config:
                axis: 1
                errors: "ignore"
            - target: casual
              config:
                axis: 1
                errors: "ignore"
          _NaNDropper:
            - target: hum
              config:
                axis: 1
                errors: "ignore"
            - target: season
              config:
                axis: 1
                errors: "ignore"

    data_explorer:
      DataExplorer:
        pipeline:
          correlation_analysis: true

  Random_Forest_Preprocessing:
    data_preparation:
      DataPreparation:
        pipeline:
          _FeatureDropper:
            - target: atemp
              config:
                axis: 1
                errors: "ignore"
          _NaNDropper:
            - target: hum
              config:
                axis: 1
                errors: "ignore"
            - target: season
              config:
                axis: 1
                errors: "ignore"
                
    data_explorer:
      DataExplorer:
        pipeline:
          correlation_analysis: true

Task3:
  Transform_dteday_to_datetime:
    data_preparation:
      DataPreparation:
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: idstools._transformer
              config:
                target: dteday
                format: "%d.%m.%Y"

  Evaluate_Model:
    model_optimization:
      ModelOptimization:
        pipeline:
          train_test_split: true
          linear_regression: true
          validation: true