default:
  Target_Data:
    _objects:
      Target:
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"
        features: ['registered', 'temp', 'atemp', 'windspeed', 'season', 'yr', 'mnth', 'weekday', 'weathersit']
  
  02_Group_By_Holyday_1:
    data_preparation:
      DataPreparation:
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: idstools._transformer
              config:
                target: dteday
                format: "%d.%m.%Y"
            - func: extract_year_from_datetime
              module: idstools._transformer
              config:
                target: dteday
            - func: group_by_value
              module: idstools._transformer
              config:
                target: holiday
                value: 1

  03_Data_Exploration_Holyday_1:
    data_explorer:
      DataExplorer:
        pipeline:
          descriptive_analysis: true
          missing_value_analysis: true
          outlier_analysis: true
          distribution_analysis: true
          scatter_analysis: true
          correlation_analysis: true
          calculate_correlation: true
          time_series_analysis: true