default:
  Target_Data:
    _objects:
      Target:
        id: 1
        input_path: "data/BikeRentalDaily.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"

  Explorer_01:
    exploration:
      DataExplorer:
        targets: [1]
        pipeline:
          - explorer: missing_values_plot
          - explorer: correlation_plot
          - explorer: correlation_analysis
            config:
              method: "pearson"
  
  Preprocessing_01:
    preparation:
      DataPreparation:
        targets: [1]
        pipeline:
          _NaNDropper:
            - target: [hum, season]

  Explorer_02:
    exploration:
      DataExplorer:
        targets: [1]
        pipeline:
          - explorer: vif_analysis

  Preprocessing_02:
    preparation:
      DataPreparation:
        targets: [1]
        pipeline:
          _OneHotEncoder:
            - target: season
              config:
                prefix: season
                dtype: "int"
                drop_first: true
            - target: weekday
              config:
                prefix: weekday
                dtype: "int"
                drop_first: true
            - target: weathersit
              config:
                prefix: weathersit
                dtype: "int"
                drop_first: true

  Explorer_03:
    exploration:
      DataExplorer:
        targets: [1]
        pipeline:
          - explorer: vif_analysis
