default:
  Target_Data:
    _objects:
      Target:
        name: Target_Data
        input_path: "data/BikeRentalDaily_train.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"

  Validation_Data:
    _objects:
      Target:
        name: Validation_Data
        input_path: "data/BikeRentalDaily_test.csv"
        input_delimiter: ";"
        index: "instant"
        label: "cnt"

  Preprocessing:
    data_preparation:
      DataPreparation:
        targets: ['Target_Data', 'Validation_Data']
        pipeline:
          _CustomTransformer:
            - func: target_to_datetime
              module: "idstools._transformer"
              config:
                target: dteday
                format: "%d.%m.%Y"
            - func: impute_season
              module: "idstools._transformer"
              config:
                target: season
                date: dteday
            - func: negative_to_nan
              module: "idstools._transformer"
              config:
                target: windspeed
            - func: process_weekday
              module: "idstools._transformer"
              config:
                target: weekday
                date: dteday
            - func: remove_outliers
              module: "idstools._transformer"
              config:
                target: cnt
            - func: standard_scaler
              module: "idstools._transformer"
              config:
                label: cnt
          _OneHotEncoder:
            - target: mnth
              config:
                prefix: mnth
                dtype: "int"
                drop_first: true
            - target: weekday
              config:
                prefix: weekday
                dtype: "int"
                drop_first: true
            - target: weathersit
              config:
                prefix: weathersit
                dtype: "int"
                drop_first: true
          _SimpleImputer:
            - target: ['hum', 'windspeed']
              config:
                strategy: "mean"
          _FeatureDropper:
            - target: ['casual', 'registered', 'temp', 'dteday', 'workingday']
              config:
                axis: 1
                errors: "ignore"

  Evaluation:
    model_optimization:
      ModelOptimization:
        targets: ['Target_Data', 'Validation_Data']
        pipeline:
          - model: LazyRegressor
            module: lazypredict.Supervised
            config:
              verbose: 0
              ignore_warnings: false
              random_state: 42
            split:
              targets: ['Target_Data']
              config:
                test_size: 0.2
                random_state: 42
            validation:
              targets: ['Target_Data', 'Validation_Data']
          
          - model: GridSearchCV
            module: sklearn.model_selection
            config:
              estimator: RandomForestRegressor
              param_grid:
                n_estimators: [100, 200, 300]
                max_features: ['auto', 'sqrt']
                max_depth: [10, 20, 30]
                min_samples_split: [2, 5, 10]
                min_samples_leaf: [1, 2, 4]
                bootstrap: [True, False]
              cv: 5
              n_jobs: -1
              verbose: 2

          - model: LinearRegression
            module: sklearn.linear_model
            config:
              fit_intercept: true
              copy_X: true
              positive: false
            split:
              targets: ['Target_Data']
              config:
                test_size: 0.2
                random_state: 42
            save:
              path: "models/LinearRegression.pkl"

          - model: "models/LinearRegression.pkl"
            validation:
              targets: ['Validation_Data']
              methods: ['r2_score', 'mae', 'actual_vs_predicted']

  Exploration:
    data_explorer:
      DataExplorer:
        target: 'Validation_Data'
        targets: ['Validation_Data']
        pipeline:
          descriptive_analysis: true
          - explorer: descriptive_analysis
            config:
              head: 10
              tail: 10
          - explorer: correlation_analysis
            config:
              method: "pearson"
          - explorer: correlation_analysis
            config:
              method: "kendall"
          - explorer: correlation_analysis
            config:
              method: "spearman"
          - explorer: vif_analysis
          - explorer: missing_values_plot
          - explorer: correlation_plot
          - explorer: outlier_plot
          - explorer: distribution_plot
          - explorer: scatter_plot
          - explorer: categorical_plot
          - explorer: time_series_plot
          - explorer: over_index_plot