data_explorer:
  console_output: True
  input:
    file: 
      path: "/home/davidrmn/Studies/introduction-data-science/data/BikeRentalDaily_train.csv"
      type: "csv"
      sep: ";"
  split_data: False
  discriptiv_analysis: True

data_preparation:

model_optimization: