data_explorer:
  console_output: True
  input_file: 
      path: "/home/davidrmn/Studies/introduction-data-science/data/BikeRentalDaily_train.csv"
      type: "csv"
      sep: ";"
  discriptiv_analysis: True

data_preparation:
  console_output: True
  input_file: 
      path: "/home/davidrmn/Studies/introduction-data-science/data/BikeRentalDaily_train.csv"
      type: "csv"
      sep: ";"
  pipeline:
    imputer: [
      {
      "variable": "hum",
      "strategy": "mean"
      }
      ]
    one_hot_encoder: [
      {
      "variable": "season",
      "prefix": "season",
      "dtype": "int"
      },
      {
      "variable": "mnth",
      "prefix": "month",
      "dtype": "int"
      }
      ]
    feature_dropper: [
      {
      "variable": "instant"
      }
      ]
    data_splitter:
      test_size: 0.2
      random_state: 42

model_optimization:
  evaluation:
    metric: "rmse"
    cv: 5