data_explorer:
  console_output: True
  input_file: 
      path: "/home/davidrmn/Studies/introduction-data-science/data/BikeRentalDaily_train.csv"
      type: "csv"
      sep: ";"
  split_data: False
  discriptiv_analysis: True

data_preparation:
  console_output: True
  input_file: 
      path: "/home/davidrmn/Studies/introduction-data-science/data/BikeRentalDaily_train.csv"
      type: "csv"
      sep: ";"
  one_hot_encode: [
    {
      target: "weekday",
      prefix: "weekday",
      dtype: "int"
    },
    {
      target: "season",
      prefix: "season",
      dtype: "int"
    }
  ]

model_optimization:
  evaluation:
    metric: "rmse"
    cv: 5