version: 1
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] - %(message)s"
handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  file_handler:
    class: logging.FileHandler
    filename: idstools.log
    level: DEBUG
    formatter: simple
loggers:
  data_explorer:
    level: DEBUG
    handlers: [console_handler, file_handler]
    propagate: False
  data_preparation:
    level: DEBUG
    handlers: [console_handler, file_handler]
    propagate: False
root:
  level: DEBUG
  handlers: [console_handler, file_handler]